/**
 * YCCĐ môn Toán lớp 6–9 theo CT GDPT 2018 / Thông tư 32/2018/TT-BGDĐT.
 * Nguồn: GIAO AN/yeucau.docx (nguyên văn, không tự thêm).
 */
const KHBD_YCCD = {
  toan: {
    "6": [
      { theme: "SỐ VÀ ĐẠI SỐ", topic: "Số tự nhiên và tập hợp các số tự nhiên. Thứ tự trong tập hợp các số tự nhiên", items: ["Sử dụng được thuật ngữ tập hợp, phần tử thuộc (không thuộc) một tập hợp; sử dụng được cách cho tập hợp.", "Nhận biết được tập hợp các số tự nhiên.", "Biểu diễn được số tự nhiên trong hệ thập phân.", "Biểu diễn được các số tự nhiên từ 1 đến 30 bằng cách sử dụng các chữ số La Mã.", "Nhận biết được (quan hệ) thứ tự trong tập hợp các số tự nhiên; so sánh được hai số tự nhiên cho trước."] },
      { theme: "SỐ VÀ ĐẠI SỐ", topic: "Các phép tính với số tự nhiên. Phép tính luỹ thừa với số mũ tự nhiên", items: ["Thực hiện được các phép tính: cộng, trừ, nhân, chia trong tập hợp số tự nhiên.", "Vận dụng được các tính chất giao hoán, kết hợp, phân phối của phép nhân đối với phép cộng trong tính toán.", "Thực hiện được phép tính luỹ thừa với số mũ tự nhiên; thực hiện được các phép nhân và phép chia hai luỹ thừa cùng cơ số với số mũ tự nhiên.", "Nhận biết được thứ tự thực hiện các phép tính.", "Vận dụng được các tính chất của phép tính (kể cả phép tính luỹ thừa với số mũ tự nhiên) để tính nhẩm, tính nhanh một cách hợp lí.", "Giải quyết được những vấn đề thực tiễn gắn với thực hiện các phép tính (ví dụ: tính tiền mua sắm, tính lượng hàng mua được từ số tiền đã có,...)."] },
      { theme: "SỐ VÀ ĐẠI SỐ", topic: "Tính chia hết trong tập hợp các số tự nhiên. Số nguyên", items: ["Nhận biết được quan hệ chia hết, khái niệm ước và bội.", "Vận dụng được dấu hiệu chia hết cho 2, 5, 9, 3 để xác định một số đã cho có chia hết cho 2, 5, 9, 3 hay không.", "Nhận biết được khái niệm số nguyên tố, hợp số.", "Thực hiện được việc phân tích một số tự nhiên lớn hơn 1 thành tích của các thừa số nguyên tố trong những trường hợp đơn giản.", "Xác định được ước chung, ước chung lớn nhất; xác định được bội chung, bội chung nhỏ nhất của hai hoặc ba số tự nhiên; nhận biết được phân số tối giản; thực hiện được phép cộng, phép trừ phân số bằng cách sử dụng ước chung lớn nhất, bội chung nhỏ nhất.", "Nhận biết được phép chia có dư, định lí về phép chia có dư.", "Vận dụng được kiến thức số học vào giải quyết những vấn đề thực tiễn (ví dụ: tính toán tiền hay lượng hàng hoá khi mua sắm, xác định số đồ vật cần thiết để sắp xếp chúng theo những quy tắc cho trước,...)."] },
      { theme: "SỐ VÀ ĐẠI SỐ", topic: "Số nguyên âm và tập hợp các số nguyên. Thứ tự trong tập hợp các số nguyên", items: ["Nhận biết được số nguyên âm, tập hợp các số nguyên.", "Biểu diễn được số nguyên trên trục số.", "Nhận biết được số đối của một số nguyên.", "Nhận biết được thứ tự trong tập hợp các số nguyên. So sánh được hai số nguyên cho trước.", "Nhận biết được ý nghĩa của số nguyên âm trong một số bài toán thực tiễn."] },
      { theme: "SỐ VÀ ĐẠI SỐ", topic: "Các phép tính với số nguyên. Tính chia hết trong  tập  hợp  các  số", items: ["Thực hiện được các phép tính: cộng, trừ, nhân, chia (chia hết) trong tập hợp các số nguyên.", "Vận dụng được các tính chất giao hoán, kết hợp, phân phối của phép nguyên"] },
      { theme: "SỐ VÀ ĐẠI SỐ", topic: "nhân đối với phép cộng, quy tắc dấu ngoặc trong tập hợp các số nguyên trong tính toán (tính viết và tính nhẩm, tính nhanh một cách hợp lí).", items: ["Nhận biết được quan hệ chia hết, khái niệm ước và bội trong tập hợp các số nguyên.", "Giải quyết được những vấn đề thực tiễn gắn với thực hiện các phép tính về số nguyên (ví dụ: tính lỗ lãi khi buôn bán,...)."] },
      { theme: "SỐ VÀ ĐẠI SỐ", topic: "Phân số. Tính chất cơ bản của phân số. So sánh phân số", items: ["Nhận biết được phân số với tử số hoặc mẫu số là số nguyên âm.", "Nhận biết được khái niệm hai phân số bằng nhau và nhận biết được quy tắc bằng nhau của hai phân số.", "Nêu được hai tính chất cơ bản của phân số.", "So sánh được hai phân số cho trước.", "Nhận biết được số đối của một phân số.", "Nhận biết được hỗn số dương."] },
      { theme: "SỐ VÀ ĐẠI SỐ", topic: "Các phép tính với phân số", items: ["Thực hiện được các phép tính cộng, trừ, nhân, chia với phân số.", "Vận dụng được các tính chất giao hoán, kết hợp, phân phối của phép nhân đối với phép cộng, quy tắc dấu ngoặc với phân số trong tính toán (tính viết và tính nhẩm, tính nhanh một cách hợp lí).", "Tính được giá trị phân số của một số cho trước và tính được một số biết giá trị phân số của số đó.", "Giải quyết được một số vấn đề thực tiễn gắn với các phép tính về phân số (ví dụ: các bài toán liên quan đến chuyển động trong Vật lí,...)."] },
      { theme: "SỐ VÀ ĐẠI SỐ", topic: "Số thập phân và các phép tính với số thập phân. Tỉ số và tỉ số phần trăm", items: ["Nhận biết được số thập phân âm, số đối của một số thập phân.", "So sánh được hai số thập phân cho trước.", "Thực hiện được các phép tính cộng, trừ, nhân, chia với số thập phân.", "Vận dụng được các tính chất giao hoán, kết hợp, phân phối của phép nhân đối với phép cộng, quy tắc dấu ngoặc với số thập phân trong tính toán (tính viết và tính nhẩm, tính nhanh một cách hợp lí).", "Thực hiện được ước lượng và làm tròn số thập phân.", "Tính được tỉ số và tỉ số phần trăm của hai đại lượng.", "Tính được giá trị phần trăm của một số cho trước và tính được một số biết giá trị phần trăm của số đó.", "Giải quyết được một số vấn đề thực tiễn gắn với các phép tính về số thập phân, tỉ số và tỉ số phần trăm (ví dụ: các bài toán liên quan đến lãi suất tín dụng, liên quan đến thành phần các chất trong Hoá học,...)."] },
      { theme: "HÌNH HỌC VÀ ĐO LƯỜNG", topic: "Nhận dạng được tam giác đều, hình vuông, lục giác đều.", items: ["Mô tả được một số yếu tố cơ bản (cạnh, góc, đường chéo) của: tam giác đều (ví dụ: ba cạnh bằng nhau, ba góc bằng nhau); hình vuông (ví dụ: bốn cạnh bằng nhau, mỗi góc là góc vuông, hai đường chéo bằng nhau); lục giác đều (ví dụ: sáu cạnh bằng nhau, sáu góc bằng nhau, ba đường chéo chính bằng nhau).", "Vẽ được tam giác đều, hình vuông bằng dụng cụ học tập."] },
      { theme: "HÌNH HỌC VÀ ĐO LƯỜNG", topic: "Hình chữ nhật, hình thoi, hình bình hành, hình thang cân", items: ["Mô tả được một số yếu tố cơ bản (cạnh, góc, đường chéo) của hình chữ nhật, hình thoi, hình bình hành, hình thang cân.", "Vẽ được hình chữ nhật, hình thoi, hình bình hành bằng các dụng cụ học tập.", "Giải quyết được một số vấn đề thực tiễn gắn với việc tính chu vi và diện tích của các hình đặc biệt nói trên (ví dụ: tính chu vi hoặc diện tích của một số đối tượng có dạng đặc biệt nói trên,...)."] },
      { theme: "HÌNH HỌC VÀ ĐO LƯỜNG", topic: "Hình có trục đối xứng", items: ["Nhận biết được trục đối xứng của một hình phẳng.", "Nhận biết được những hình phẳng trong tự nhiên có trục đối xứng (khi quan sát trên hình ảnh 2 chiều)."] },
      { theme: "HÌNH HỌC VÀ ĐO LƯỜNG", topic: "Hình có tâm đối xứng", items: ["Nhận biết được tâm đối xứng của một hình phẳng.", "Nhận biết được những hình phẳng trong thế giới tự nhiên có tâm đối xứng (khi quan sát trên hình ảnh 2 chiều)."] },
      { theme: "HÌNH HỌC VÀ ĐO LƯỜNG", topic: "Vai trò của đối xứng trong thế giới tự nhiên", items: ["Nhận biết được tính đối xứng trong Toán học, tự nhiên, nghệ thuật, kiến trúc, công nghệ chế tạo,...", "Nhận biết được vẻ đẹp của thế giới tự nhiên biểu hiện qua tính đối xứng (ví dụ: nhận biết vẻ đẹp của một số loài thực vật, động vật trong tự nhiên có tâm đối xứng hoặc có trục đối xứng)."] },
      { theme: "HÌNH HỌC VÀ ĐO LƯỜNG", topic: "Điểm, đường thẳng, tia", items: ["Nhận biết được những quan hệ cơ bản giữa điểm, đường thẳng: điểm thuộc đường thẳng, điểm không thuộc đường thẳng; tiên đề về đường thẳng đi qua hai điểm phân biệt.", "Nhận biết được khái niệm hai đường thẳng cắt nhau, song song.", "Nhận biết được khái niệm ba điểm thẳng hàng, ba điểm không thẳng hàng.", "Nhận biết được khái niệm điểm nằm giữa hai điểm.", "Nhận biết được khái niệm tia."] },
      { theme: "HÌNH HỌC VÀ ĐO LƯỜNG", topic: "Đoạn thẳng. Độ dài đoạn thẳng", items: ["Nhận biết được khái niệm đoạn thẳng, trung điểm của đoạn thẳng, độ dài đoạn thẳng."] },
      { theme: "HÌNH HỌC VÀ ĐO LƯỜNG", topic: "Góc. Các góc đặc biệt. Số đo góc", items: ["Nhận biết được khái niệm góc, điểm trong của góc (không đề cập đến góc lõm).", "Nhận biết được các góc đặc biệt (góc vuông, góc nhọn, góc tù, góc bẹt).", "Nhận biết được khái niệm số đo góc."] },
      { theme: "MỘT SỐ YẾU TỐ THỐNG KÊ VÀ XÁC SUẤT", topic: "Thu thập, phân loại, biểu diễn dữ liệu theo các tiêu chí cho trước", items: ["Thực hiện được việc thu thập, phân loại dữ liệu theo các tiêu chí cho trước từ những nguồn: bảng biểu, kiến thức trong các môn học khác.", "Nhận biết được tính hợp lí của dữ liệu theo các tiêu chí đơn giản."] },
      { theme: "MỘT SỐ YẾU TỐ THỐNG KÊ VÀ XÁC SUẤT", topic: "Hình thành và giải quyết vấn đề đơn giản xuất hiện từ các số liệu và biểu đồ thống kê đã có", items: ["Nhận ra được vấn đề hoặc quy luật đơn giản dựa trên phân tích các số liệu thu được ở dạng: bảng thống kê; biểu đồ tranh; biểu đồ dạng cột/cột kép (column chart).", "Giải quyết được những vấn đề đơn giản liên quan đến các số liệu thu được ở dạng: bảng thống kê; biểu đồ tranh; biểu đồ dạng cột/cột kép (column chart).", "Nhận biết được mối liên hệ giữa thống kê với những kiến thức trong các môn học trong Chương trình lớp 6 (ví dụ: Lịch sử và Địa lí lớp 6, Khoa học tự nhiên lớp 6,...) và trong thực tiễn (ví dụ: khí hậu, giá cả thị trường,...)."] },
      { theme: "MỘT SỐ YẾU TỐ THỐNG KÊ VÀ XÁC SUẤT", topic: "Một số yếu tố xác suất", items: ["Làm quen với một số mô hình xác suất đơn giản. Làm quen với việc mô tả xác suất"] },
      { theme: "MỘT SỐ YẾU TỐ THỐNG KÊ VÀ XÁC SUẤT", topic: "Mô tả xác suất (thực nghiệm) của khả năng xảy ra nhiều lần của một sự kiện trong một số mô hình xác suất đơn giản", items: ["Sử dụng được phân số để mô tả xác suất (thực nghiệm) của khả năng xảy ra nhiều lần thông qua kiểm đếm số lần lặp lại của khả năng đó trong một số mô hình xác suất đơn giản."] },
      { theme: "MỘT SỐ YẾU TỐ THỐNG KÊ VÀ XÁC SUẤT", topic: "Thực hành trong phòng máy tính với phần mềm toán học (nếu nhà trường có điều kiện thực hiện)", items: ["Sử dụng được phần mềm để vẽ biểu đồ tranh; biểu đồ dạng cột/cột kép."] },
      { theme: "HOẠT ĐỘNG THỰC HÀNH VÀ TRẢI NGHIỆM", topic: "Hoạt động 1: Tìm hiểu một số kiến thức về tài chính:", items: ["Làm quen với việc gửi tiền tiết kiệm và vay vốn ngân hàng; tính lỗ, lãi và dư nợ; thực hành tính lãi suất trong tiền gửi tiết kiệm và vay vốn."] }
    ],
    "7": [
      { theme: "SỐ VÀ ĐẠI SỐ", topic: "Số hữu tỉ và tập hợp các số hữu tỉ. Thứ tự trong tập hợp các số hữu tỉ", items: ["Nhận biết được số hữu tỉ và lấy được ví dụ về số hữu tỉ.", "Nhận biết được tập hợp các số hữu tỉ.", "Biểu diễn được số hữu tỉ trên trục số.", "Nhận biết được số đối của một số hữu tỉ."] },
      { theme: "SỐ VÀ ĐẠI SỐ", topic: "Các phép tính với số hữu tỉ", items: ["Thực hiện được các phép tính: cộng, trừ, nhân, chia trong tập hợp số hữu tỉ.", "Mô tả được phép tính luỹ thừa với số mũ tự nhiên của một số hữu tỉ và một số tính chất của phép tính đó (tích và thương của hai luỹ thừa cùng cơ số, luỹ thừa của luỹ thừa).", "Mô tả được thứ tự thực hiện các phép tính, quy tắc dấu ngoặc, quy tắc chuyển vế trong tập hợp số hữu tỉ.", "Vận dụng được các tính chất giao hoán, kết hợp, phân phối của phép nhân đối với phép cộng, quy tắc dấu ngoặc với số hữu tỉ trong tính toán (tính viết và tính nhẩm, tính nhanh một cách hợp lí).", "Giải quyết được một số vấn đề thực tiễn gắn với các phép tính về số hữu tỉ (ví dụ: các bài toán liên quan đến chuyển động trong Vật lí, trong đo đạc,...)."] },
      { theme: "SỐ VÀ ĐẠI SỐ", topic: "Căn bậc hai số học", items: ["Nhận biết được khái niệm căn bậc hai số học của một số không âm.", "Tính được giá trị (đúng hoặc gần đúng) căn bậc hai số học của một số nguyên dương bằng máy tính cầm tay."] },
      { theme: "SỐ VÀ ĐẠI SỐ", topic: "Số vô tỉ. Số thực", items: ["Nhận biết được số thập phân hữu hạn và số thập phân vô hạn tuần hoàn.", "Nhận biết được số vô tỉ, số thực, tập hợp các số thực.", "Nhận biết được trục số thực và biểu diễn được số thực trên trục số trong trường hợp thuận lợi.", "Nhận biết được số đối của một số thực.", "Nhận biết được thứ tự trong tập hợp các số thực.", "Nhận biết được giá trị tuyệt đối của một số thực.", "Thực hiện được ước lượng và làm tròn số căn cứ vào độ chính xác cho trước."] },
      { theme: "SỐ VÀ ĐẠI SỐ", topic: "Tỉ lệ thức và dãy tỉ số bằng nhau", items: ["Nhận biết được tỉ lệ thức và các tính chất của tỉ lệ thức.", "Vận dụng được tính chất của tỉ lệ thức trong giải toán.", "Nhận biết được dãy tỉ số bằng nhau.", "Vận dụng được tính chất của dãy tỉ số bằng nhau trong giải toán (ví dụ: chia một số thành các phần tỉ lệ với các số cho trước,...)."] },
      { theme: "SỐ VÀ ĐẠI SỐ", topic: "Giải toán về đại lượng tỉ lệ", items: ["Giải được một số bài toán đơn giản về đại lượng tỉ lệ thuận (ví dụ: bài toán về tổng sản phẩm thu được và năng suất lao động,...).", "Giải được một số bài toán đơn giản về đại lượng tỉ lệ nghịch (ví dụ: bài toán về thời gian hoàn thành kế hoạch và năng suất lao động,...)."] },
      { theme: "SỐ VÀ ĐẠI SỐ", topic: "Biểu thức đại số", items: ["Nhận biết được biểu thức số.", "Nhận biết được biểu thức đại số.", "Tính được giá trị của một biểu thức đại số."] },
      { theme: "SỐ VÀ ĐẠI SỐ", topic: "Đa thức một biến", items: ["Nhận biết được định nghĩa đa thức một biến.", "Nhận biết được cách biểu diễn đa thức một biến; xác định được bậc của đa thức một biến.", "Tính được giá trị của đa thức khi biết giá trị của biến.", "Nhận biết được khái niệm nghiệm của đa thức một biến.", "Thực hiện được các phép tính: phép cộng, phép trừ, phép nhân, phép chia trong tập hợp các đa thức một biến; vận dụng được những tính chất của các phép tính đó trong tính toán."] },
      { theme: "HÌNH HỌC VÀ ĐO LƯỜNG", topic: "Hình hộp chữ nhật và hình lập phương", items: ["Mô tả được một số yếu tố cơ bản (đỉnh, cạnh, góc, đường chéo) của hình hộp chữ nhật và hình lập phương.", "Giải quyết được một số vấn đề thực tiễn gắn với việc tính thể tích, diện tích xung quanh của hình hộp chữ nhật, hình lập phương (ví dụ: tính thể tích hoặc diện tích xung quanh của một số đồ vật quen thuộc có dạng hình hộp chữ nhật, hình lập phương,...)."] },
      { theme: "HÌNH HỌC VÀ ĐO LƯỜNG", topic: "Lăng trụ đứng tam giác, lăng trụ đứng tứ giác", items: ["Mô tả được hình lăng trụ đứng tam giác, hình lăng trụ đứng tứ giác (ví dụ: hai mặt đáy là song song; các mặt bên đều là hình chữ nhật) và tạo lập được hình lăng trụ đứng tam giác, hình lăng trụ đứng tứ giác.", "Tính được diện tích xung quanh, thể tích của hình lăng trụ đứng tam giác, hình lăng trụ đứng tứ giác.", "Giải quyết được một số vấn đề thực tiễn gắn với việc tính thể tích, diện tích xung quanh của một lăng trụ đứng tam giác, hình lăng trụ đứng tứ"] },
      { theme: "HÌNH HỌC VÀ ĐO LƯỜNG", topic: "Góc ở vị trí đặc biệt. Tia phân giác của một góc", items: ["Nhận biết được các góc ở vị trí đặc biệt (hai góc kề bù, hai góc đối đỉnh).", "Nhận biết được tia phân giác của một góc.", "Nhận biết được cách vẽ tia phân giác của một góc bằng dụng cụ học tập."] },
      { theme: "HÌNH HỌC VÀ ĐO LƯỜNG", topic: "Hai đường thẳng song song. Tiên đề Euclid về đường thẳng song song", items: ["Mô tả được một số tính chất của hai đường thẳng song song.", "Mô tả được dấu hiệu song song của hai đường thẳng thông qua cặp góc đồng vị, cặp góc so le trong.", "Nhận biết được tiên đề Euclid về đường thẳng song song."] },
      { theme: "HÌNH HỌC VÀ ĐO LƯỜNG", topic: "Khái niệm định lí, chứng minh một định lí", items: ["Nhận biết được thế nào là một định lí, chứng minh một định lí."] },
      { theme: "HÌNH HỌC VÀ ĐO LƯỜNG", topic: "Tam giác. Tam giác bằng nhau. Tam giác cân. Quan hệ giữa đường vuông góc và đường xiên. Các đường đồng quy của tam giác", items: ["Giải thích được định lí về tổng các góc trong một tam giác bằng 180o.", "Nhận biết được liên hệ về độ dài của ba cạnh trong một tam giác.", "Nhận biết được khái niệm hai tam giác bằng nhau.", "Giải thích được các trường hợp bằng nhau của hai tam giác, của hai tam giác vuông.", "Mô tả được tam giác cân và giải thích được tính chất của tam giác cân (ví dụ: hai cạnh bên bằng nhau; hai góc đáy bằng nhau).", "Nhận biết được khái niệm: đường vuông góc và đường xiên; khoảng cách từ một điểm đến một đường thẳng. Giải thích được quan hệ giữa"] },
      { theme: "HÌNH HỌC VÀ ĐO LƯỜNG", topic: "đường vuông góc và đường xiên dựa trên mối quan hệ giữa cạnh và góc đối trong tam giác (đối diện với góc lớn hơn là cạnh lớn hơn và ngược lại).", items: ["Nhận biết được đường trung trực của một đoạn thẳng và tính chất cơ bản của đường trung trực.", "Nhận biết được: các đường đặc biệt trong tam giác (đường trung tuyến, đường cao, đường phân giác, đường trung trực); sự đồng quy của các đường đặc biệt đó."] },
      { theme: "HÌNH HỌC VÀ ĐO LƯỜNG", topic: "Diễn đạt được lập luận và chứng minh hình học trong những trường hợp đơn giản (ví dụ: lập luận và chứng minh được các đoạn thẳng bằng nhau, các góc bằng nhau từ các điều kiện ban đầu liên quan đến tam giác,...).", items: ["Giải quyết được một số vấn đề thực tiễn liên quan đến ứng dụng của hình học như: đo, vẽ, tạo dựng các hình đã học."] },
      { theme: "MỘT SỐ YẾU TỐ THỐNG KÊ VÀ XÁC SUẤT", topic: "Lựa chọn và biểu diễn được dữ liệu vào bảng, biểu đồ thích hợp ở dạng: biểu đồ hình quạt tròn (cho sẵn) (pie chart); biểu đồ đoạn thẳng (line graph).", items: ["Nhận biết được những dạng biểu diễn khác nhau cho một tập dữ liệu."] },
      { theme: "MỘT SỐ YẾU TỐ THỐNG KÊ VÀ XÁC SUẤT", topic: "Hình thành và giải quyết vấn đề đơn giản xuất hiện từ các số liệu và biểu đồ thống kê đã có", items: ["Nhận ra được vấn đề hoặc quy luật đơn giản dựa trên phân tích các số liệu thu được ở dạng: biểu đồ hình quạt tròn (cho sẵn) (pie chart); biểu đồ đoạn thẳng (line graph).", "Giải quyết được những vấn đề đơn giản liên quan đến các số liệu thu được ở dạng: biểu đồ hình quạt tròn (cho sẵn) (pie chart); biểu đồ đoạn thẳng (line graph).", "Nhận biết được mối liên hệ giữa thống kê với những kiến thức trong các môn học khác trong Chương trình lớp 7 (ví dụ: Lịch sử và Địa lí lớp 7, Khoa học tự nhiên lớp 7,...) và trong thực tiễn (ví dụ: môi trường, y học, tài chính,...)."] },
      { theme: "MỘT SỐ YẾU TỐ THỐNG KÊ VÀ XÁC SUẤT", topic: "Một số yếu tố xác", items: ["Làm quen với biến cố ngẫu"] },
      { theme: "MỘT SỐ YẾU TỐ THỐNG KÊ VÀ XÁC SUẤT", topic: "Thực hành trong phòng máy tính với phần mềm toán học (nếu nhà trường có điều kiện thực hiện)", items: ["Sử dụng được phần mềm để tổ chức dữ liệu vào biểu đồ hình quạt tròn (pie chart); biểu đồ đoạn thẳng (line graph)."] },
      { theme: "HOẠT ĐỘNG THỰC HÀNH VÀ TRẢI NGHIỆM", topic: "Thực hành tính toán việc tăng, giảm theo giá trị phần trăm của một mặt hàng hoặc một kế hoạch sản xuất, kinh doanh.", items: ["Làm quen với giao dịch ngân hàng.", "Làm quen với thuế và việc tính thuế."] }
    ],
    "8": [
      { theme: "SỐ VÀ ĐẠI SỐ", topic: "Đa thức nhiều biến. Các phép toán cộng, trừ, nhân, chia các đa thức nhiều biến", items: ["Nhận biết được các khái niệm về đơn thức, đa thức nhiều biến.", "Tính được giá trị của đa thức khi biết giá trị của các biến.", "Thực hiện được việc thu gọn đơn thức, đa thức.", "Thực hiện được phép nhân đơn thức với đa thức và phép chia hết một đơn thức cho một đơn thức.", "Thực hiện được các phép tính: phép cộng, phép trừ, phép nhân các đa thức nhiều biến trong những trường hợp đơn giản.", "Thực hiện được phép chia hết một đa thức cho một đơn thức trong những trường hợp đơn giản."] },
      { theme: "SỐ VÀ ĐẠI SỐ", topic: "Hằngđẳngthức đáng nhớ", items: ["Nhận biết được các khái niệm: đồng nhất thức, hằng đẳng thức.", "Mô tả được các hằng đẳng thức: bình phương của tổng và hiệu; hiệu hai"] },
      { theme: "SỐ VÀ ĐẠI SỐ", topic: "Phân thức đại số. Tính chất cơ bản của phân thức đại số. Các phép toán cộng, trừ, nhân, chia các phân thức đại số", items: ["Nhận biết được các khái niệm cơ bản về phân thức đại số: định nghĩa; điều kiện xác định; giá trị của phân thức đại số; hai phân thức bằng nhau.", "Mô tả được những tính chất cơ bản của phân thức đại số.", "Thực hiện được các phép tính: phép cộng, phép trừ, phép nhân, phép chia đối với hai phân thức đại số.", "Vận dụng được các tính chất giao hoán, kết hợp, phân phối của phép nhân đối với phép cộng, quy tắc dấu ngoặc với phân thức đại số trong tính toán."] },
      { theme: "SỐ VÀ ĐẠI SỐ", topic: "Hàm số và đồ thị", items: ["Nhận biết được những mô hình thực tế dẫn đến khái niệm hàm số.", "Tính được giá trị của hàm số khi hàm số đó xác định bởi công thức.", "Xác định được toạ độ của một điểm trên mặt phẳng toạ độ; xác định được một điểm trên mặt phẳng toạ độ khi biết toạ độ của nó.", "Nhận biết được đồ thị hàm số."] },
      { theme: "SỐ VÀ ĐẠI SỐ", topic: "Hàm   số   bậc   nhất y = ax + b (a  0) và đồ thị. Hệ số góc của đường thẳng y = ax + b (a  0).", items: ["Thiết lập được bảng giá trị của hàm số bậc nhất y = ax + b (a  0).", "Vẽ được đồ thị của hàm số bậc nhất y = ax + b (a  0).", "Nhận biết được khái niệm hệ số góc của đường thẳng y = ax + b (a  0).", "Sử dụng được hệ số góc của đường thẳng để nhận biết và giải thích"] },
      { theme: "SỐ VÀ ĐẠI SỐ", topic: "Hiểu được khái niệm phương trình bậc nhất một ẩn và cách giải.", items: ["Giải quyết được một số vấn đề thực tiễn gắn với phương trình bậc nhất (ví dụ: các bài toán liên quan đến chuyển động trong Vật lí, các bài toán liên quan đến Hoá học,...)."] },
      { theme: "HÌNH HỌC VÀ ĐO LƯỜNG", topic: "Mô tả (đỉnh, mặt đáy, mặt bên, cạnh bên), tạo lập được hình chóp tam giác đều và hình chóp tứ giác đều.", items: ["Tính được diện tích xung quanh, thể tích của một hình chóp tam giác đều và hình chóp tứ giác đều.", "Giải quyết được một số vấn đề thực tiễn gắn với việc tính thể tích, diện tích xung quanh của hình chóp tam giác đều và hình chóp tứ giác đều (ví dụ: tính thể tích hoặc diện tích xung quanh của một số đồ vật quen thuộc có dạng hình chóp tam giác đều và hình chóp tứ giác đều,...)."] },
      { theme: "HÌNH HỌC VÀ ĐO LƯỜNG", topic: "Định lí Pythagore", items: ["Giải thích được định lí Pythagore.", "Tính được độ dài cạnh trong tam giác vuông bằng cách sử dụng định lí Pythagore."] },
      { theme: "HÌNH HỌC VÀ ĐO LƯỜNG", topic: "Tứ giác", items: ["Mô tả được tứ giác, tứ giác lồi.", "Giải thích được định lí về tổng các góc trong một tứ giác lồi bằng 360o."] },
      { theme: "HÌNH HỌC VÀ ĐO LƯỜNG", topic: "Tính chất và dấu hiệu nhận biết các tứ giác đặc biệt", items: ["Giải thích được tính chất về góc kề một đáy, cạnh bên, đường chéo của hình thang cân.", "Nhận biết được dấu hiệu để một hình thang là hình thang cân (ví dụ: hình thang có hai đường chéo bằng nhau là hình thang cân).", "Giải thích được tính chất về cạnh đối, góc đối, đường chéo của hình bình hành.", "Nhận biết được dấu hiệu để một tứ giác là hình bình hành (ví dụ: tứ giác có hai đường chéo cắt nhau tại trung điểm của mỗi đường là hình bình hành).", "Giải thích được tính chất về hai đường chéo của hình chữ nhật.", "Nhận biết được dấu hiệu để một hình bình hành là hình chữ nhật (ví dụ: hình bình hành có hai đường chéo bằng nhau là hình chữ nhật).", "Giải thích được tính chất về đường chéo của hình thoi.", "Nhận biết được dấu hiệu để một hình bình hành là hình thoi (ví dụ: hình bình hành có hai đường chéo vuông góc với nhau là hình thoi).", "Giải thích được tính chất về hai đường chéo của hình vuông.", "Nhận biết được dấu hiệu để một hình chữ nhật là hình vuông (ví dụ:"] },
      { theme: "HÌNH HỌC VÀ ĐO LƯỜNG", topic: "Định lí Thalès trong tam giác", items: ["Giải thích được định lí Thalès trong tam giác (định lí thuận và đảo).", "Mô tả được định nghĩa đường trung bình của tam giác. Giải thích được tính chất đường trung bình của tam giác (đường trung bình của tam giác thì song song với cạnh thứ ba và bằng nửa cạnh đó).", "Giải thích được tính chất đường phân giác trong của tam giác.", "Tính được độ dài đoạn thẳng bằng cách sử dụng định lí Thalès.", "Giải quyết được một số vấn đề thực tiễn gắn với việc vận dụng định lí Thalès (ví dụ: tính khoảng cách giữa hai vị trí)."] },
      { theme: "HÌNH HỌC VÀ ĐO LƯỜNG", topic: "Tam giác đồng dạng", items: ["Mô tả được định nghĩa của hai tam giác đồng dạng.", "Giải thích được các trường hợp đồng dạng của hai tam giác, của hai tam giác vuông.", "Giải quyết được một số vấn đề thực tiễn gắn với việc vận dụng kiến thức về hai tam giác đồng dạng (ví dụ: tính độ dài đường cao hạ xuống cạnh huyền trong tam giác vuông bằng cách sử dụng mối quan hệ giữa đường cao đó với tích của hai hình chiếu của hai cạnh góc vuông lên cạnh huyền; đo gián tiếp chiều cao của vật; tính khoảng cách giữa hai vị trí trong đó có một vị trí không thể tới được,...)."] },
      { theme: "HÌNH HỌC VÀ ĐO LƯỜNG", topic: "Hình đồng dạng", items: ["Nhận biết được hình đồng dạng phối cảnh (hình vị tự), hình đồng dạng qua các hình ảnh cụ thể.", "Nhận biết được vẻ đẹp trong tự nhiên, nghệ thuật, kiến trúc, công nghệ chế tạo,... biểu hiện qua hình đồng dạng."] },
      { theme: "MỘT SỐ YẾU TỐ THỐNG KÊ VÀ XÁC SUẤT", topic: "Lựa chọn và biểu diễn được dữ liệu vào bảng, biểu đồ thích hợp ở dạng: bảng thống kê; biểu đồ tranh; biểu đồ dạng cột/cột kép (column chart), biểu đồ hình quạt tròn (cho sẵn) (pie chart); biểu đồ đoạn thẳng (line graph).", items: ["Nhận biết được mối liên hệ toán học đơn giản giữa các số liệu đã được biểu diễn. Từ đó, nhận biết được số liệu không chính xác trong những ví dụ đơn giản.", "So sánh được các dạng biểu diễn khác nhau cho một tập dữ liệu.", "Mô tả được cách chuyển dữ liệu từ dạng biểu diễn này sang dạng biểu diễn khác."] },
      { theme: "MỘT SỐ YẾU TỐ THỐNG KÊ VÀ XÁC SUẤT", topic: "Hình thành và giải quyết vấn đề đơn giản xuất hiện từ các số liệu và biểu đồ thống kê đã có", items: ["Phát hiện được vấn đề hoặc quy luật đơn giản dựa trên phân tích các số liệu thu được ở dạng: bảng thống kê; biểu đồ tranh; biểu đồ dạng cột/cột kép (column chart), biểu đồ hình quạt tròn (pie chart); biểu đồ đoạn thẳng (line graph).", "Giải quyết được những vấn đề đơn giản liên quan đến các số liệu thu được ở dạng: bảng thống kê; biểu đồ tranh; biểu đồ dạng cột/cột kép (column chart), biểu đồ hình quạt tròn (pie chart); biểu đồ đoạn thẳng (line graph).", "Nhận biết được mối liên hệ giữa thống kê với những kiến thức trong các môn học khác trong Chương trình lớp 8 (ví dụ: Lịch sử và Địa lí lớp 8, Khoa học tự nhiên lớp 8,...) và trong thực tiễn."] },
      { theme: "MỘT SỐ YẾU TỐ THỐNG KÊ VÀ XÁC SUẤT", topic: "Mô tả xác suất của biến cố ngẫu nhiên trong một số ví dụ đơn giản. Mối liên hệ giữa xác suất thực nghiệm của một biến cố với xác suất của biến cố đó", items: ["Sử dụng được tỉ số để mô tả xác suất của một biến cố ngẫu nhiên trong một số ví dụ đơn giản.", "Nhận biết được mối liên hệ giữa xác suất thực nghiệm của một biến cố với xác suất của biến cố đó thông qua một số ví dụ đơn giản."] },
      { theme: "MỘT SỐ YẾU TỐ THỐNG KÊ VÀ XÁC SUẤT", topic: "Thực hành trong phòng máy tính với phần mềm toán học (nếu nhà trường có điều kiện thực hiện)", items: ["Sử dụng được phần mềm để vẽ biểu đồ.", "Sử dụng được phần mềm để xác định được tần số.", "Sử dụng được phần mềm mô tả thí nghiệm ngẫu nhiên."] },
      { theme: "HOẠT ĐỘNG THỰC HÀNH VÀ TRẢI NGHIỆM", topic: "Lập kế hoạch chi tiêu của bản thân.", items: ["Làm quen với bài toán về đầu tư cá nhân (xác định vốn đầu tư để đạt được lãi suất mong đợi)."] }
    ],
    "9": [
      { theme: "SỐ VÀ ĐẠI SỐ", topic: "Căn bậc hai và căn bậc ba của số thực", items: ["Nhận biết được khái niệm về căn bậc hai của số thực không âm, căn bậc ba của một số thực.", "Tính được giá trị (đúng hoặc gần đúng) căn bậc hai, căn bậc ba của một số hữu tỉ bằng máy tính cầm tay.", "Thực hiện được một số phép tính đơn giản về căn bậc hai của số thực không âm (căn bậc hai của một bình phương, căn bậc hai của một tích, căn bậc hai của một thương, đưa thừa số ra ngoài dấu căn bậc hai, đưa thừa số vào trong dấu căn bậc hai)."] },
      { theme: "SỐ VÀ ĐẠI SỐ", topic: "Căn thức bậc hai và căn thức bậc ba của biểu thức đại số", items: ["Nhận biết được khái niệm về căn thức bậc hai và căn thức bậc ba của một biểu thức đại số.", "Thực hiện được một số phép biến đổi đơn giản về căn thức bậc hai của biểu thức đại số (căn thức bậc hai của một bình phương, căn thức bậc hai của một tích, căn thức bậc hai của một thương, trục căn thức ở mẫu)."] },
      { theme: "SỐ VÀ ĐẠI SỐ", topic: "Hàm số y = ax2 (a  0) và đồ thị", items: ["Thiết lập được bảng giá trị của hàm số y = ax2 (a  0).", "Vẽ được đồ thị của hàm số y = ax2 (a  0).", "Nhận biết được tính đối xứng (trục) và trục đối xứng của đồ thị hàm số"] },
      { theme: "SỐ VÀ ĐẠI SỐ", topic: "y = ax2 (a  0).", items: ["Giải quyết được một số vấn đề thực tiễn gắn với hàm số y = ax2 (a  0)"] },
      { theme: "SỐ VÀ ĐẠI SỐ", topic: "Phương trình quy về phương trình bậc nhất một ẩn", items: ["Giải được phương trình tích có dạng (a1x + b1).(a2x + b2) = 0.", "Giải được phương trình chứa ẩn ở mẫu quy về phương trình bậc nhất."] },
      { theme: "SỐ VÀ ĐẠI SỐ", topic: "Phương trình và hệ phương trình bậc nhất hai ẩn", items: ["Nhận biết được khái niệm phương trình bậc nhất hai ẩn, hệ hai phương trình bậc nhất hai ẩn.", "Nhận biết được khái niệm nghiệm của hệ hai phương trình bậc nhất hai ẩn.", "Giải được hệ hai phương trình bậc nhất hai ẩn.", "Tính được nghiệm của hệ hai phương trình bậc nhất hai ẩn bằng máy tính cầm tay.", "Giải quyết được một số vấn đề thực tiễn gắn với hệ hai phương trình bậc nhất hai ẩn (ví dụ: các bài toán liên quan đến cân bằng phản ứng trong Hoá học,...)."] },
      { theme: "SỐ VÀ ĐẠI SỐ", topic: "Phương trình bậc hai một ẩn. Định lí Viète", items: ["Nhận biết được khái niệm phương trình bậc hai một ẩn. Giải được phương trình bậc hai một ẩn.", "Tính được nghiệm phương trình bậc hai một ẩn bằng máy tính cầm tay.", "Giải thích được định lí Viète và ứng dụng (ví dụ: tính nhẩm nghiệm của phương trình bậc hai, tìm hai số biết tổng và tích của chúng,...).", "Vận dụng được phương trình bậc hai vào giải quyết bài toán thực tiễn."] },
      { theme: "SỐ VÀ ĐẠI SỐ", topic: "trình bậc nhất một ẩn", items: ["Nhận biết được bất đẳng thức và mô tả được một số tính chất cơ bản của bất đẳng thức (tính chất bắc cầu; liên hệ giữa thứ tự và phép cộng, phép nhân).", "Nhận biết được khái niệm bất phương trình bậc nhất một ẩn, nghiệm của bất phương trình bậc nhất một ẩn.", "Giải được bất phương trình bậc nhất một ẩn."] },
      { theme: "HÌNH HỌC VÀ ĐO LƯỜNG", topic: "Mô tả (tâm, bán kính), tạo lập được hình cầu, mặt cầu. Nhận biết được phần chung của mặt phẳng và hình cầu.", items: ["Tính được diện tích xung quanh của hình trụ, hình nón, diện tích mặt cầu.", "Tính được thể tích của hình trụ, hình nón, hình cầu.", "Giải quyết được một số vấn đề thực tiễn gắn với việc tính diện tích xung quanh, thể tích của hình trụ, hình nón, hình cầu (ví dụ: tính thể tích hoặc diện tích xung quanh của một số đồ vật quen thuộc có dạng hình trụ, hình nón, hình cầu,...)."] },
      { theme: "HÌNH HỌC VÀ ĐO LƯỜNG", topic: "Tỉ số lượng giác của góc nhọn. Một số hệ thức về cạnh và góc trong tam giác vuông", items: ["Nhận biết được các giá trị sin (sine), côsin (cosine), tang (tangent), côtang (cotangent) của góc nhọn.", "Giải thích được tỉ số lượng giác của các góc nhọn đặc biệt (góc 30o, 45o, 60o) và của hai góc phụ nhau.", "Tính được giá trị (đúng hoặc gần đúng) tỉ số lượng giác của góc nhọn bằng máy tính cầm tay.", "Giải thích được một số hệ thức về cạnh và góc trong tam giác vuông (cạnh góc vuông bằng cạnh huyền nhân với sin góc đối hoặc nhân với côsin góc kề; cạnh góc vuông bằng cạnh góc vuông kia nhân với tang góc đối hoặc nhân với côtang góc kề).", "Giải quyết được một số vấn đề thực tiễn gắn với tỉ số lượng giác của góc nhọn (ví dụ: Tính độ dài đoạn thẳng, độ lớn góc và áp dụng giải tam giác vuông,...)."] },
      { theme: "HÌNH HỌC VÀ ĐO LƯỜNG", topic: "Đường tròn. Vị trí tương đối của hai đường tròn", items: ["Nhận biết được tâm đối xứng, trục đối xứng của đường tròn.", "So sánh được độ dài của đường kính và dây.", "Mô tả được ba vị trí tương đối của hai đường tròn (hai đường tròn cắt nhau, hai đường tròn tiếp xúc nhau, hai đường tròn không giao nhau)."] },
      { theme: "HÌNH HỌC VÀ ĐO LƯỜNG", topic: "Vị trí tương đối của đường thẳng và đường tròn. Tiếp tuyến của đường tròn", items: ["Mô tả được ba vị trí tương đối của đường thẳng và đường tròn (đường thẳng và đường tròn cắt nhau, đường thẳng và đường tròn tiếp xúc nhau, đường thẳng và đường tròn không giao nhau).", "Giải thích được dấu hiệu nhận biết tiếp tuyến của đường tròn và tính"] },
      { theme: "HÌNH HỌC VÀ ĐO LƯỜNG", topic: "Góc ở tâm, góc nội tiếp", items: ["Nhận biết được góc ở tâm, góc nội tiếp.", "Giải thích được mối liên hệ giữa số đo của cung với số đo góc ở tâm, số đo góc nội tiếp.", "Giải thích được mối liên hệ giữa số đo góc nội tiếp và số đo góc ở tâm cùng chắn một cung."] },
      { theme: "HÌNH HỌC VÀ ĐO LƯỜNG", topic: "Đường tròn ngoại tiếp tam giác. Đường tròn nội tiếp tam giác", items: ["Nhận biết được định nghĩa đường tròn ngoại tiếp tam giác.", "Xác định được tâm và bán kính đường tròn ngoại tiếp tam giác, trong đó có tâm và bán kính đường tròn ngoại tiếp tam giác vuông, tam giác đều.", "Nhận biết được định nghĩa đường tròn nội tiếp tam giác.", "Xác định được tâm và bán kính đường tròn nội tiếp tam giác, trong đó có tâm và bán kính đường tròn nội tiếp tam giác đều."] },
      { theme: "HÌNH HỌC VÀ ĐO LƯỜNG", topic: "Tứ giác nội tiếp", items: ["Nhận biết được tứ giác nội tiếp đường tròn và giải thích được định lí về tổng hai góc đối của tứ giác nội tiếp bằng 180o.", "Xác định được tâm và bán kính đường tròn ngoại tiếp hình chữ nhật, hình vuông.", "Tính được độ dài cung tròn, diện tích hình quạt tròn, diện tích hình vành khuyên (hình giới hạn bởi hai đường tròn đồng tâm).", "Giải quyết được một số vấn đề thực tiễn gắn với đường tròn (ví dụ: một số bài toán liên quan đến chuyển động tròn trong Vật lí; tính được diện tích một số hình phẳng có thể đưa về những hình phẳng gắn với hình tròn, chẳng hạn hình viên phân,...)."] },
      { theme: "HÌNH HỌC VÀ ĐO LƯỜNG", topic: "Nhận dạng được đa giác đều.", items: ["Nhận biết được phép quay.", "Mô tả được các phép quay giữ nguyên hình đa giác đều.", "Nhận biết được những hình phẳng đều trong tự nhiên, nghệ thuật, kiến trúc, công nghệ chế tạo,...", "Nhận biết được vẻ đẹp của thế giới tự nhiên biểu hiện qua tính đều."] },
      { theme: "MỘT SỐ YẾU TỐ THỐNG KÊ VÀ XÁC SUẤT", topic: "Bảng tần số tương đối, biểu đồ tần số tương đối", items: ["Thiết lập được bảng tần số, biểu đồ tần số (biểu diễn các giá trị và tần số của chúng ở dạng biểu đồ cột hoặc biểu đồ đoạn thẳng).", "Giải thích được ý nghĩa và vai trò của tần số trong thực tiễn.", "Xác định được tần số tương đối (relative frequency) của một giá trị.", "Thiết lập được bảng tần số tương đối, biểu đồ tần số tương đối (biểu diễn các giá trị và tần số tương đối của chúng ở dạng biểu đồ cột hoặc biểu đồ hình quạt tròn).", "Giải thích được ý nghĩa và vai trò của tần số tương đối trong thực tiễn.", "Thiết lập được bảng tần số ghép nhóm, bảng tần số tương đối ghép nhóm.", "Thiết lập được biểu đồ tần số tương đối ghép nhóm (histogram) (ở dạng biểu đồ cột hoặc biểu đồ đoạn thẳng).", "Nhận biết được mối liên hệ giữa thống kê với những kiến thức của các môn học khác trong Chương trình lớp 9 và trong thực tiễn."] },
      { theme: "MỘT SỐ YẾU TỐ THỐNG KÊ VÀ XÁC SUẤT", topic: "Phép thử ngẫu nhiên và không gian mẫu. Xác suất của biến cố trong một số mô hình xác suất đơn giản", items: ["Nhận biết được phép thử ngẫu nhiên và không gian mẫu.", "Tính được xác suất của biến cố bằng cách kiểm đếm số trường hợp có thể và số trường hợp thuận lợi trong một số mô hình xác suất đơn giản."] },
      { theme: "HOẠT ĐỘNG THỰC HÀNH VÀ TRẢI NGHIỆM", topic: "Thực hành lập kế hoạch đầu tư cá nhân.", items: ["Làm quen với bảo hiểm.", "Làm quen với bài toán về tăng trưởng (xác định vốn đầu tư để đạt được tỉ lệ tăng trưởng mong đợi)."] }
    ]
  }
};

function normalizeYccdText(value) {
  return String(value || "").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, " ").trim();
}

function scoreYccdBlock(block, haystack) {
  const topic = normalizeYccdText(block.topic);
  const theme = normalizeYccdText(block.theme);
  let score = 0;
  topic.split(" ").filter(w => w.length > 3).forEach(w => { if (haystack.includes(w)) score += 3; });
  theme.split(" ").filter(w => w.length > 3).forEach(w => { if (haystack.includes(w)) score += 1; });
  (block.items || []).forEach(item => {
    normalizeYccdText(item).split(" ").filter(w => w.length > 4).slice(0, 8).forEach(w => { if (haystack.includes(w)) score += 1; });
  });
  return score;
}

function getOfficialYccd({ subjectId, grade, topic, visionText } = {}) {
  const subject = String(subjectId || "").toLowerCase();
  if (subject !== "toan" && subject !== "math") return "";
  const gradeKey = String(grade || "");
  const blocks = KHBD_YCCD.toan && KHBD_YCCD.toan[gradeKey];
  if (!Array.isArray(blocks) || !blocks.length) return "";
  const haystack = normalizeYccdText([topic, visionText].filter(Boolean).join(" "));
  let picked = blocks;
  if (haystack) {
    const ranked = blocks.map(block => ({ block, score: scoreYccdBlock(block, haystack) })).sort((a, b) => b.score - a.score);
    const best = ranked.filter(row => row.score > 0).slice(0, 3).map(row => row.block);
    if (best.length) picked = best;
  }
  const lines = [
    "Nguồn: Chương trình GDPT 2018 môn Toán, ban hành kèm Thông tư 32/2018/TT-BGDĐT (YCCĐ Toán lớp " + gradeKey + "). Chỉ dùng nguyên văn các YCCĐ dưới đây, không thêm kiến thức ngoài danh sách."
  ];
  picked.forEach(block => {
    const head = [block.theme, block.topic].filter(Boolean).join(" — ");
    if (head) lines.push("Chủ đề: " + head);
    (block.items || []).forEach(item => lines.push("- " + item));
  });
  return lines.join("\n");
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = { KHBD_YCCD, getOfficialYccd };
}
