<?php
$configPath = __DIR__ . '/api/config.php';
$samplePath = __DIR__ . '/api/config.sample.php';
$schemaPath = __DIR__ . '/database_schema.sql';
$message = '';
$messageType = 'info';

function h($value)
{
    return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8');
}

function write_config($host, $name, $user, $pass, $adminKey)
{
    global $configPath;
    $content = "<?php\n"
        . "// Generated by setup.php. Do not publish this file with real credentials.\n\n"
        . "define('DB_HOST', " . var_export($host, true) . ");\n"
        . "define('DB_NAME', " . var_export($name, true) . ");\n"
        . "define('DB_USER', " . var_export($user, true) . ");\n"
        . "define('DB_PASS', " . var_export($pass, true) . ");\n\n"
        . "define('ADMIN_KEY', " . var_export($adminKey, true) . ");\n"
        . "define('APP_SESSION_NAME', 'giangbai_session');\n"
        . "define('APP_TIMEZONE', 'Asia/Ho_Chi_Minh');\n\n"
        . "// Google Drive for Giao & Nhan bai. Fill these values directly on the hosting.\n"
        . "define('GOOGLE_DRIVE_CREDENTIALS_JSON', '');\n"
        . "define('GOOGLE_DRIVE_TOKEN_JSON', '');\n"
        . "define('GOOGLE_DRIVE_ROOT_FOLDER_ID', '');\n"
        . "define('GOOGLE_DRIVE_SHARE_MODE', 'private');\n"
        . "define('SUBMISSION_MAX_FILE_MB', 25);\n";

    return file_put_contents($configPath, $content, LOCK_EX) !== false;
}

function import_schema(PDO $pdo, $schemaPath)
{
    if (!file_exists($schemaPath)) return 'Không tìm thấy database_schema.sql, đã bỏ qua bước tạo bảng.';

    $sql = file_get_contents($schemaPath);
    if (!$sql) return 'Không đọc được database_schema.sql, đã bỏ qua bước tạo bảng.';

    $statements = array_filter(array_map('trim', preg_split('/;\s*[\r\n]+/', $sql)));
    foreach ($statements as $statement) {
        if ($statement !== '') $pdo->exec($statement);
    }
    return 'Đã tạo/cập nhật bảng database.';
}

$alreadyInstalled = file_exists($configPath);

if ($_SERVER['REQUEST_METHOD'] === 'POST' && !$alreadyInstalled) {
    $host = trim($_POST['db_host'] ?? 'localhost');
    $name = trim($_POST['db_name'] ?? '');
    $user = trim($_POST['db_user'] ?? '');
    $pass = (string)($_POST['db_pass'] ?? '');
    $adminKey = trim($_POST['admin_key'] ?? '');
    $importTables = !empty($_POST['import_tables']);

    if ($host === '' || $name === '' || $user === '' || $adminKey === '') {
        $message = 'Vui lòng nhập đủ DB_HOST, DB_NAME, DB_USER và ADMIN_KEY.';
        $messageType = 'error';
    } else {
        try {
            $pdo = new PDO(
                'mysql:host=' . $host . ';dbname=' . $name . ';charset=utf8mb4',
                $user,
                $pass,
                [
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                    PDO::ATTR_EMULATE_PREPARES => false,
                ]
            );

            if (!is_dir(__DIR__ . '/api')) {
                throw new RuntimeException('Không tìm thấy thư mục api/. Hãy upload đầy đủ thư mục api trước.');
            }

            if (!write_config($host, $name, $user, $pass, $adminKey)) {
                throw new RuntimeException('Không ghi được api/config.php. Hãy kiểm tra quyền ghi file trên hosting.');
            }

            $schemaMsg = $importTables ? import_schema($pdo, $schemaPath) : 'Chưa import bảng vì bạn không chọn tùy chọn này.';
            $alreadyInstalled = true;
            $message = 'Cài đặt thành công. ' . $schemaMsg . ' Bây giờ có thể mở admin.html để cấp tài khoản học sinh.';
            $messageType = 'success';
        } catch (Throwable $e) {
            $message = 'Cài đặt thất bại: ' . $e->getMessage();
            $messageType = 'error';
        }
    }
}
?>
<!DOCTYPE html>
<html lang="vi">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cài đặt hệ thống học sinh</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>

<body class="min-h-screen bg-slate-100 p-4 text-slate-900">
    <main class="mx-auto max-w-2xl">
        <section class="mt-8 rounded-lg border border-slate-200 bg-white p-6 shadow-lg">
            <div class="mb-6">
                <p class="text-sm font-bold uppercase tracking-widest text-blue-700">GiangBai Setup</p>
                <h1 class="mt-1 text-2xl font-bold">Tạo cấu hình PHP cho hosting</h1>
                <p class="mt-2 text-sm leading-6 text-slate-600">Trang này dùng một lần để tạo <code>api/config.php</code> và kiểm tra kết nối MySQL.</p>
            </div>

            <?php if ($message): ?>
                <div class="mb-5 rounded border px-4 py-3 text-sm <?php echo $messageType === 'success' ? 'border-green-200 bg-green-50 text-green-800' : 'border-red-200 bg-red-50 text-red-700'; ?>">
                    <?php echo h($message); ?>
                </div>
            <?php endif; ?>

            <?php if ($alreadyInstalled): ?>
                <div class="rounded border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-800">
                    <p class="font-bold">Hệ thống đã có <code>api/config.php</code>.</p>
                    <p>Nếu muốn cài lại, hãy xóa file <code>api/config.php</code> trên hosting rồi mở lại trang này.</p>
                    <p class="mt-2">Sau khi cài xong nên xóa hoặc đổi tên <code>setup.php</code> để tránh người khác mở lại.</p>
                </div>
                <div class="mt-5 flex gap-3">
                    <a href="admin.html" class="rounded bg-blue-600 px-4 py-2 text-sm font-bold text-white hover:bg-blue-700">Mở admin.html</a>
                    <a href="login.html" class="rounded border border-slate-300 bg-white px-4 py-2 text-sm font-bold text-slate-700 hover:bg-slate-50">Mở login.html</a>
                </div>
            <?php else: ?>
                <?php if (!file_exists($samplePath)): ?>
                    <div class="mb-5 rounded border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
                        Không thấy <code>api/config.sample.php</code>. Hãy upload đầy đủ thư mục <code>api/</code>.
                    </div>
                <?php endif; ?>

                <form method="post" class="space-y-4">
                    <label class="block text-sm font-bold text-slate-700">
                        DB_HOST
                        <input name="db_host" value="localhost" required class="mt-1 w-full rounded border border-slate-300 px-3 py-2 outline-none focus:border-blue-600">
                    </label>
                    <label class="block text-sm font-bold text-slate-700">
                        DB_NAME
                        <input name="db_name" required class="mt-1 w-full rounded border border-slate-300 px-3 py-2 outline-none focus:border-blue-600" placeholder="cpaneluser_giangbai">
                    </label>
                    <label class="block text-sm font-bold text-slate-700">
                        DB_USER
                        <input name="db_user" required class="mt-1 w-full rounded border border-slate-300 px-3 py-2 outline-none focus:border-blue-600" placeholder="cpaneluser_gbuser">
                    </label>
                    <label class="block text-sm font-bold text-slate-700">
                        DB_PASS
                        <input name="db_pass" type="password" class="mt-1 w-full rounded border border-slate-300 px-3 py-2 outline-none focus:border-blue-600" placeholder="Mật khẩu database">
                    </label>
                    <label class="block text-sm font-bold text-slate-700">
                        ADMIN_KEY
                        <input name="admin_key" required class="mt-1 w-full rounded border border-slate-300 px-3 py-2 outline-none focus:border-blue-600" placeholder="Mật khẩu riêng để mở admin.html">
                    </label>
                    <label class="flex items-start gap-2 rounded border border-slate-200 bg-slate-50 p-3 text-sm font-semibold text-slate-700">
                        <input name="import_tables" type="checkbox" checked class="mt-1">
                        <span>Tự tạo/cập nhật bảng bằng <code>database_schema.sql</code></span>
                    </label>
                    <button class="w-full rounded bg-blue-600 px-4 py-3 text-sm font-bold text-white hover:bg-blue-700">Kiểm tra và tạo config.php</button>
                </form>
            <?php endif; ?>
        </section>
    </main>
</body>

</html>
