<?php
/** Proxy Gemini dành riêng cho Canvas: key luôn chỉ được dùng ở máy chủ. */
require_once __DIR__ . '/helpers.php';
require_once __DIR__ . '/ai_runtime_config.php';
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type, X-User-Account');
if (($_SERVER['REQUEST_METHOD'] ?? '') === 'OPTIONS') { http_response_code(204); exit; }
function canvas_user_account(array $body = []): string {$value=$body['user_account']??($_GET['user_account']??($_SERVER['HTTP_X_USER_ACCOUNT']??''));return trim(rawurldecode((string)$value));}
function canvas_user_keys(string $account): array {global $pdo;if($account===''||!isset($pdo)||!$pdo instanceof PDO)return [[],[]];$prefix=strstr($account,'@',true)?:$account;$stmt=$pdo->prepare('SELECT username, email, gemini_keys FROM users WHERE username = ? OR email = ? OR username = ? LIMIT 1');$stmt->execute([$account,$account,$prefix]);$row=$stmt->fetch()?:[];return [$row,parse_stored_api_keys($row['gemini_keys']??null)];}
function canvas_gemini_call(string $model,string $key,string $encoded,int $timeout): array {$url='https://generativelanguage.googleapis.com/v1beta/models/'.rawurlencode($model).':generateContent?key='.rawurlencode($key);$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_POST=>true,CURLOPT_HTTPHEADER=>['Content-Type: application/json'],CURLOPT_POSTFIELDS=>$encoded,CURLOPT_CONNECTTIMEOUT=>10,CURLOPT_TIMEOUT=>$timeout]);$raw=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);$curlError=curl_error($ch);curl_close($ch);$decoded=is_string($raw)&&$raw!==''?json_decode($raw,true):null;$error=is_array($decoded)?(string)($decoded['error']['message']??('Gemini HTTP '.$status)):($curlError!==''?'Máy chủ không gọi được Gemini: '.$curlError:'Gemini trả về dữ liệu không hợp lệ.');return ['ok'=>is_array($decoded)&&$status>=200&&$status<300,'body'=>$decoded,'status'=>$status?:502,'error'=>$error];}
$method=$_SERVER['REQUEST_METHOD']??'';$body=$method==='POST'?json_body():[];$account=canvas_user_account($body);$action=trim((string)($body['action']??($_GET['action']??'')));
if($action==='key_status'){[$user,$userKeys]=canvas_user_keys($account);respond(['ok'=>true,'user_account'=>$account,'key_count'=>count($userKeys),'gemini_key_count'=>count($userKeys),'masked_keys'=>array_values(array_filter(array_map('mask_user_api_key',$userKeys))),'has_user_keys'=>!empty($userKeys)]);}
if($method!=='POST')respond(['ok'=>false,'error'=>'Method not allowed.'],405);
$payload=$body['payload']??null;if(!is_array($payload)||empty($payload['contents']))respond(['ok'=>false,'error'=>'Thiếu nội dung gửi Gemini.'],422);$encoded=json_encode($payload,JSON_UNESCAPED_UNICODE);if(!is_string($encoded)||strlen($encoded)>8*1024*1024)respond(['ok'=>false,'error'=>'Tài liệu quá lớn để Canvas gửi tới Gemini.'],413);
$runtime=load_ai_runtime_config();$systemKeys=$runtime['gemini_keys']??[];if(empty($runtime['gemini_enabled'])||empty($systemKeys))respond(['ok'=>false,'error'=>'Gemini Canvas chưa được Admin cấu hình khóa hệ thống.'],503);$timeout=max(10,min(90,(int)($body['timeout']??75)));$tier=($body['tier']??'')==='high_reasoning'?'high_reasoning':'heavy_io';$preferredModel=trim((string)($body['preferred_model']??'gemini-3.8-flash'));if(!preg_match('/^gemini-[a-z0-9._-]+$/i',$preferredModel))$preferredModel='gemini-3.8-flash';[$user,$userKeys]=canvas_user_keys($account);$last=['status'=>502,'error'=>'Không gọi được Gemini Canvas.'];$quotaKeyIndexes=[];
if($tier==='high_reasoning'&&$userKeys)foreach($userKeys as $index=>$key){$attempt=canvas_gemini_call($preferredModel,$key,$encoded,$timeout);if($attempt['ok'])respond(['ok'=>true,'body'=>$attempt['body'],'model'=>$preferredModel,'tier'=>'user_key','key_index'=>$index+1,'total_user_keys'=>count($userKeys),'rotation_count'=>count($quotaKeyIndexes),'quota_key_indexes'=>$quotaKeyIndexes,'fallback_used'=>false]);if($attempt['status']===429||preg_match('/quota|resource exhausted|rate limit/i',$attempt['error']))$quotaKeyIndexes[]=$index+1;$last=$attempt;}
foreach($systemKeys as $key){$attempt=canvas_gemini_call('gemini-3-flash-preview',$key,$encoded,$timeout);if($attempt['ok'])respond(['ok'=>true,'body'=>$attempt['body'],'model'=>'gemini-3-flash-preview','tier'=>$tier==='heavy_io'?'system_key':'fallback_system','fallback_used'=>$tier==='high_reasoning','total_user_keys'=>count($userKeys),'rotation_count'=>count($quotaKeyIndexes),'quota_key_indexes'=>$quotaKeyIndexes]);$last=$attempt;}
respond(['ok'=>false,'error'=>$last['error']],$last['status']>=400&&$last['status']<500?$last['status']:502);
