<?php
require_once __DIR__ . '/helpers.php'; if(session_status()===PHP_SESSION_NONE)session_start(); if(empty($_SESSION['user_id']))respond(['error'=>'Chưa đăng nhập.'],401);
function ensure_duyet_giao_an_sessions(PDO $pdo):void{$pdo->exec("CREATE TABLE IF NOT EXISTS duyet_giao_an_sessions (id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,dot_duyet VARCHAR(80) NOT NULL DEFAULT '',thang VARCHAR(30) NOT NULL DEFAULT '',nam_hoc VARCHAR(30) NOT NULL DEFAULT '',to_chuyen_mon VARCHAR(255) NOT NULL DEFAULT '',summary TEXT NOT NULL,session_data LONGTEXT NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_duyet_giao_an_user (user_id),INDEX idx_duyet_giao_an_updated (updated_at)) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");}
function department_plan(PDO $pdo,int $uid,int $planId=0):?array{$sql='SELECT id,plan_key,title,school_year,data_json,updated_at FROM phancong_chuyenmon WHERE owner_id=?';$args=[$uid];if($planId){$sql.=' AND id=?';$args[]=$planId;}$s=$pdo->prepare($sql.' ORDER BY updated_at DESC,id DESC LIMIT 1');$s->execute($args);$r=$s->fetch();if(!$r||!is_array($r['data']=json_decode($r['data_json'],true)))return null;return $r;}
function department_teachers(array $data):array{$subjects=[];foreach(($data['subjects']??[]) as $s)if(is_array($s)&&!empty($s['key']))$subjects[(string)$s['key']]=(string)($s['name']??$s['label']??$s['key']);$out=[];foreach(($data['teachers']??[]) as $t){if(!is_array($t))continue;$as=[];foreach(($t['assignments']??[]) as $key=>$classes){$classes=is_array($classes)?array_values(array_filter(array_map('strval',$classes))):[];if($classes)$as[]=['subject'=>$subjects[(string)$key]??(string)$key,'classes'=>$classes];}$out[]=['id'=>(string)($t['user_id']??$t['id']??''),'name'=>trim((string)($t['name']??$t['full_name']??'')),'email'=>trim((string)($t['email']??'')),'role'=>trim((string)($t['role']??'')),'assignments'=>$as];}return $out;}
function plan_has_teacher(array $teachers,string $id):bool{foreach($teachers as $t)if($id!==''&&(string)($t['id']??'')===$id)return true;return false;}
$uid=(int)$_SESSION['user_id'];$method=$_SERVER['REQUEST_METHOD']??'GET';$action=$_GET['action']??'';try{ensure_duyet_giao_an_sessions($pdo);
if($method==='GET'&&$action==='get_department_teachers'){$plan=department_plan($pdo,$uid,(int)($_GET['plan_id']??0));if(!$plan)respond(['ok'=>true,'plan'=>null,'teachers'=>[]]);respond(['ok'=>true,'plan'=>['id'=>(int)$plan['id'],'title'=>$plan['title'],'plan_key'=>$plan['plan_key'],'school_year'=>$plan['school_year'],'updated_at'=>$plan['updated_at']],'teachers'=>department_teachers($plan['data'])]);}
if($method==='GET'&&$action==='get_ppct_catalog'){$teacherId=trim((string)($_GET['teacher_id']??''));$subject=trim((string)($_GET['subject']??''));$grade=trim((string)($_GET['grade']??''));$year=trim((string)($_GET['academic_year']??''));$school=trim((string)($_GET['school_name']??''));if($teacherId===''||$subject===''||$grade==='')respond(['error'=>'Thiếu giáo viên, môn hoặc khối lớp.'],422);$plan=department_plan($pdo,$uid,(int)($_GET['plan_id']??0));if(!$plan||!plan_has_teacher(department_teachers($plan['data']),$teacherId))respond(['error'=>'Giáo viên không thuộc kế hoạch phân công đang chọn.'],403);$q=$pdo->prepare('SELECT id,subject,grade,academic_year,school_name,rows_json,source_json,updated_at FROM teacher_ppct_catalogs WHERE owner_user_id=? AND subject=? AND grade=? AND academic_year=? AND school_name=? ORDER BY updated_at DESC LIMIT 1');$q->execute([(int)$teacherId,$subject,$grade,$year,$school]);$r=$q->fetch();if($r){$r['rows']=json_decode($r['rows_json'],true)?:[];$r['source']=json_decode($r['source_json'],true)?:[];unset($r['rows_json'],$r['source_json']);}respond(['ok'=>true,'catalog'=>$r]);}
if($method==='GET'&&$action==='list'){$s=$pdo->prepare('SELECT id,dot_duyet,thang,nam_hoc,to_chuyen_mon,summary,created_at,updated_at FROM duyet_giao_an_sessions WHERE user_id=? ORDER BY updated_at DESC');$s->execute([$uid]);respond(['ok'=>true,'sessions'=>$s->fetchAll()]);}
if($method==='GET'&&isset($_GET['id'])){$s=$pdo->prepare('SELECT * FROM duyet_giao_an_sessions WHERE id=? AND user_id=?');$s->execute([(int)$_GET['id'],$uid]);$r=$s->fetch();if(!$r)respond(['error'=>'Không tìm thấy đợt duyệt.'],404);$r['session_data']=json_decode($r['session_data'],true)?:[];respond(['ok'=>true,'session'=>$r]);}
if($method==='POST'&&$action==='delete'){$b=json_body();$s=$pdo->prepare('DELETE FROM duyet_giao_an_sessions WHERE id=? AND user_id=?');$s->execute([(int)($b['id']??0),$uid]);respond(['ok'=>true]);}
if($method==='POST'){$b=json_body();$data=$b['session_data']??null;if(!is_array($data))respond(['error'=>'Dữ liệu đợt duyệt không hợp lệ.'],422);$data['version']=2;$vals=[trim((string)($b['dot_duyet']??'')),trim((string)($b['thang']??'')),trim((string)($b['nam_hoc']??'')),trim((string)($b['to_chuyen_mon']??'')),trim((string)($b['summary']??'')),json_encode($data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)];$id=(int)($b['id']??0);if($id){$s=$pdo->prepare('UPDATE duyet_giao_an_sessions SET dot_duyet=?,thang=?,nam_hoc=?,to_chuyen_mon=?,summary=?,session_data=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=?');$s->execute([...$vals,$id,$uid]);if(!$s->rowCount())respond(['error'=>'Không tìm thấy đợt duyệt.'],404);}else{$s=$pdo->prepare('INSERT INTO duyet_giao_an_sessions(user_id,dot_duyet,thang,nam_hoc,to_chuyen_mon,summary,session_data)VALUES(?,?,?,?,?,?,?)');$s->execute([$uid,...$vals]);$id=(int)$pdo->lastInsertId();}$s=$pdo->prepare('SELECT id,dot_duyet,thang,nam_hoc,to_chuyen_mon,summary,created_at,updated_at FROM duyet_giao_an_sessions WHERE id=?');$s->execute([$id]);respond(['ok'=>true,'session'=>$s->fetch()]);}
respond(['error'=>'Method not allowed.'],405);}catch(Throwable $e){respond(['error'=>'Không thể xử lý dữ liệu duyệt giáo án.'],500);}
