<?php
// Teacher-owned Appendix-3 catalog. Authentication comes exclusively from the
// server session: deliberately do not accept an owner/account field from JS.
header('Content-Type: application/json; charset=utf-8');
header('Access-Control-Allow-Methods: GET, PUT, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type');
if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'OPTIONS') { http_response_code(204); exit; }
require_once __DIR__ . '/helpers.php';
if (session_status() === PHP_SESSION_NONE) session_start();
function ppct_reply(array $data, int $code=200): void { http_response_code($code); echo json_encode($data, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); exit; }
function ppct_teacher(PDO $pdo): array { $id=(int)($_SESSION['user_id']??0); if(!$id) ppct_reply(['error'=>'Cần đăng nhập tài khoản giáo viên.'],401); $q=$pdo->prepare("SELECT id FROM users WHERE id=? AND role='teacher' AND is_active=1 LIMIT 1");$q->execute([$id]);$u=$q->fetch();if(!$u)ppct_reply(['error'=>'Chỉ giáo viên được quản lý PPCT.'],403);return $u; }
function ppct_table(PDO $pdo): void { $pdo->exec("CREATE TABLE IF NOT EXISTS teacher_ppct_catalogs (id INT AUTO_INCREMENT PRIMARY KEY, owner_user_id INT NOT NULL, subject VARCHAR(80) NOT NULL, grade VARCHAR(20) NOT NULL, academic_year VARCHAR(30) NOT NULL DEFAULT '', rows_json LONGTEXT NOT NULL, source_json TEXT NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uq_teacher_ppct_catalog (owner_user_id,subject,grade,academic_year), INDEX idx_teacher_ppct_owner (owner_user_id), CONSTRAINT fk_teacher_ppct_owner FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE CASCADE) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"); }
try { $teacher=ppct_teacher($pdo);ppct_table($pdo);$method=$_SERVER['REQUEST_METHOD']??'GET'; if($method==='GET'){ $subject=trim((string)($_GET['subject']??''));$grade=trim((string)($_GET['grade']??''));$year=trim((string)($_GET['academic_year']??''));if($subject===''||$grade==='')ppct_reply(['error'=>'Thiếu môn hoặc khối lớp.'],422);if($year!==''){ $q=$pdo->prepare('SELECT * FROM teacher_ppct_catalogs WHERE owner_user_id=? AND subject=? AND grade=? AND academic_year=? LIMIT 1');$q->execute([(int)$teacher['id'],$subject,$grade,$year]); } else { $q=$pdo->prepare('SELECT * FROM teacher_ppct_catalogs WHERE owner_user_id=? AND subject=? AND grade=? ORDER BY updated_at DESC,id DESC LIMIT 1');$q->execute([(int)$teacher['id'],$subject,$grade]); }$row=$q->fetch();if(!$row)ppct_reply(['ok'=>true,'catalog'=>null]);$row['rows']=json_decode($row['rows_json'],true);$row['source']=json_decode($row['source_json'],true);unset($row['rows_json'],$row['source_json']);ppct_reply(['ok'=>true,'catalog'=>$row]);}
if($method!=='PUT')ppct_reply(['error'=>'Method not allowed.'],405);$body=json_body();$subject=trim((string)($body['subject']??''));$grade=trim((string)($body['grade']??''));$year=trim((string)($body['academic_year']??''));$rows=$body['rows']??null;$source=$body['source']??[];if($subject===''||$grade===''||!is_array($rows))ppct_reply(['error'=>'Dữ liệu PPCT không hợp lệ.'],422);if(count($rows)>1000)ppct_reply(['error'=>'Danh mục PPCT vượt giới hạn.'],422);foreach($rows as $row)if(!is_array($row)||empty($row['id'])||empty($row['title']))ppct_reply(['error'=>'Mỗi dòng PPCT cần mã ổn định và tên bài.'],422);$rj=json_encode(array_values($rows),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);$sj=json_encode(is_array($source)?$source:[],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);$q=$pdo->prepare('INSERT INTO teacher_ppct_catalogs (owner_user_id,subject,grade,academic_year,rows_json,source_json) VALUES (?,?,?,?,?,?) ON DUPLICATE KEY UPDATE rows_json=VALUES(rows_json),source_json=VALUES(source_json),updated_at=CURRENT_TIMESTAMP');$q->execute([(int)$teacher['id'],$subject,$grade,$year,$rj,$sj]);$q=$pdo->prepare('SELECT id,subject,grade,academic_year,updated_at FROM teacher_ppct_catalogs WHERE owner_user_id=? AND subject=? AND grade=? AND academic_year=?');$q->execute([(int)$teacher['id'],$subject,$grade,$year]);ppct_reply(['ok'=>true,'catalog'=>$q->fetch()]);
} catch(Throwable $e) { ppct_reply(['error'=>'Không thể lưu danh mục PPCT.'],500); }
